### PR TITLE
Revenue Daily Update

### PR DESCRIPTION
**Pull request by Jitendra-Deshmukh**
#45 Revenue drop down list is different and add summary for all MoS, DXR, Mammo

### CODE REVIEW

**Comment by Jitendra-Deshmukh** [comment]
Revenue Update 8th july

**Comment by alokmodak** [comment]
Please file a issue no

**Comment by Jitendra-Deshmukh** [comment]
#76 Add product group name in the dropdown list of revenue - Added Names in the list

#75 Revenue - Change Month Title to Month and year ex.Jan-15 - Changed

#74 Highlight Current month Bar in chart created for Revenue - Edited

**Comment by Jitendra-Deshmukh** [comment]
image

**Pull request merged**
